README.md
SUMMARY.md
examples/cli/README.md
readme/the-dev-environment.md
readme/the-protocol.md
readme/the-roadmap.md

- Bring details about the monaco protocol into the landing page
- Add a basic roadmap of upcoming work
- Give high level overview of what the protocol does
- Add information about markets available for development

updated documentation on the monaco protocol

---

examples/cli/README.md
readme/the-client.md
readme/the-protocol.md
readme/the-roadmap.md

- Updates for `0.2.1` release of the protocol

update docs for `0.2.1` protocol release

---

readme/the-admin-client
readme/the-client.md
readme/the-protocol.md

- Updates SDK docs for the admin client release
- Includes section on the admin client
- Updates the protocol section with information about operators

Admin Client Overview Documentation

---

examples/cli-admin/package-lock.json
examples/cli-admin/package.json
examples/cli-admin/src/market_create.ts
examples/cli-admin/src/market_create_verbose.ts
examples/cli-admin/src/market_open.ts
examples/cli/package-lock.json
examples/cli/package.json
examples/cli/src/get_market_prices.ts
examples/cli/src/place_against_order.ts
examples/cli/src/place_for_order.ts
examples/cli/src/utils.ts
examples/nextjs/package.json
examples/nextjs/yarn.lock

- Bump client to `1.1.4`
- Bump admin client to `0.2.1`
- `openMarket` admin example
- Update `market_create` to include clearly defined `const`
- Add `market_create_verbose` to demonstrate each step of the market creation process
- Resolve https://github.com/MonacoProtocol/sdk/issues/33

Updates for protocol version `0.2.3`

---

examples/cli-admin/package-lock.json
examples/cli-admin/package.json
examples/cli/package-lock.json
examples/cli/package.json

add ts-node as dep

---

examples/cli-admin/README.md
examples/cli-admin/package-lock.json
examples/cli-admin/package.json
examples/cli-admin/src/utils.ts
examples/cli/README.md
examples/cli/package-lock.json
examples/cli/package.json
examples/cli/src/utils.ts

- Updates to 2.0.0 of the client including `mainnet` program ID
- Updates to 1.0.0 of the admin client
- Returns additional debug information when running scripts:
- Protocol type
- RPC node
- Wallet PublicKey
- Provides feedback if `PROTOCOL_TYPE` not set
- Update READMEs
```
npm run getOrder FiTshzBZb91Q2dDuxgZgTmKnHv9sXNocbJrWd9btqRaW
> @monaco-protocol/examples@1.0.0 getOrder
> ts-node src/get_order.ts FiTshzBZb91Q2dDuxgZgTmKnHv9sXNocbJrWd9btqRaW
Supplied arguments:
{
"betOrderPk": "FiTshzBZb91Q2dDuxgZgTmKnHv9sXNocbJrWd9btqRaW"
}
⚠️  PROTOCOL_TYPE env variable not set ⚠️
Set with:
export PROTOCOL_TYPE=stable
export PROTOCOL_TYPE=release
```
```
npm run getOrder FiTshzBZb91Q2dDuxgZgTmKnHv9sXNocbJrWd9btqRaW
> @monaco-protocol/examples@1.0.0 getOrder
> ts-node src/get_order.ts …
```

update to 2.0.0 of the client, 1.0.0 admin, and add protocol switcher

---

README.md

sec3 audit

---

examples/cli/src/cancel_order.ts
examples/cli/src/cancel_orders_for_market.ts
examples/cli/src/get_balances.ts
examples/cli/src/get_market.ts
examples/cli/src/get_market_accounts.ts
examples/cli/src/get_market_outcome_titles.ts
examples/cli/src/get_market_outcomes.ts
examples/cli/src/get_market_position.ts
examples/cli/src/get_market_prices.ts
examples/cli/src/get_markets_by_event.ts
examples/cli/src/get_markets_by_mint_token.ts
examples/cli/src/get_markets_by_status.ts
examples/cli/src/get_order.ts
examples/cli/src/get_orders_by_status.ts
examples/cli/src/get_trades_for_market.ts
examples/cli/src/get_trades_for_order.ts
examples/cli/src/place_against_order.ts
examples/cli/src/place_for_order.ts

- Pass in args directly rather than define them as a const

reduce arg consts

---

SUMMARY.md
readme/understanding-market-prices.md

- Guide detailing the nuances of market prices

docs: market prices and market summary

---

README.md
SUMMARY.md
readme/built-on-monaco.md

- Adding in Sandstorm hackathon builds

docs: update built on monaco

---

examples/cli-admin/package-lock.json
examples/cli-admin/package.json
examples/cli-admin/src/market_close.ts
examples/cli/package-lock.json
examples/cli/package.json

- Update clients on cli for latests protocol release
- Add a close market script to the admin examples

feat: market close script and client bumps

---

readme/the-dev-environment.md

- Updated information on deployed devnet programs and example market schedule

docs: updated information about dev environments

---

examples/cli/src/get_market_summary.ts

- Useful additional information to expose when understanding market numbers

feat: return escrow value on getMarketSummary cli example

---

deep-dives/protocol-fees.md

- Some commits missed in Gitbook << >> Github syncing

Gitbook resync

---

readme/the-admin-client.md
readme/the-client.md

chore: update gitbook urls for the clients

---

README.md
readme/the-protocol.md

- Link out to all audit reports

chore: update sec3 audit info

---

examples/README.md
examples/cli-admin/README.md
examples/cli/README.md
examples/nextjs/README.md

- Adds unified example for getting up and running with an rpc-node through helius

docs: getting started - rpc node docs

---

readme/the-roadmap.md

- Update roadmap with completed items
- Add in progress
- Add coming soon

docs: update roadmap

---

README.md
readme/built-on-monaco.md

- Update the intro docs to include some new information and focus on the key benefits of the protocol

docs: update intro docs

---

examples/cli/package.json
examples/cli/src/markets/get_market_positions.ts

- CLI script to get all market positions on a market

feat: get market positions example

---

examples/README.md

- Adding in shyft as an RPC provider in quick start guide

docs: additional RPC info

---

examples/cli/package-lock.json
examples/cli/package.json
examples/cli/src/markets/get_market.ts
examples/cli/src/markets/get_market_accounts.ts
examples/cli/src/markets/get_market_matching_pools.ts
examples/cli/src/markets/get_market_outcomes.ts
examples/cli/src/markets/get_market_position.ts
examples/cli/src/markets/get_market_positions.ts
examples/cli/src/markets/get_market_price_ladder.ts
examples/cli/src/markets/get_market_prices.ts
examples/cli/src/markets/get_market_status_count.ts
examples/cli/src/markets/get_market_summary.ts
examples/cli/src/markets/get_markets_by_event.ts
examples/cli/src/markets/get_markets_by_mint_token.ts
examples/cli/src/markets/get_markets_by_status.ts
examples/cli/src/orders/build_and_place_order_with_fees.ts
examples/cli/src/orders/get_order.ts
examples/cli/src/orders/place_for_order.ts
examples/cli/src/orders/place_multiple_orders.ts
examples/cli/src/parsers/parsers.ts
examples/cli/src/products/create_product.ts
examples/cli/src/products/get_all_product_balances_by_mint.ts
examples/cli/src/products/get_all_products.ts
examples/cli/src/products/get_all_products_by_authority.ts
examples/cli/src/products/get_all_products_by_payer.ts
examples/cli/src/products/update_product_auth.ts
examples/cli/src/products/update_product_escrow.ts
examples/cli/src/products/update_product_rate.ts
examples/cli/src/utils/utils.ts

- Upgrades CLI example client and anchor
- Example script for adding fees and compute limit to order placement
- `npm run placeOrderWithFees <marketPk>` 
- `npm run placeOrderWithFees DC66iQdxsFvjJ5VrkTiat2wfVqbVSiTj881ATPcVhjUg` 
- And run some much needed formatting...

docs: example order placement with fees
